//
// Created by paladin on 12/12/19.
//

#ifndef GLMINECRAFT3_SELECT_PROFILE_H
#define GLMINECRAFT3_SELECT_PROFILE_H


//#define PROFILE_NETWORKING
 #define PROFILE_GAME


#endif //GLMINECRAFT3_SELECT_PROFILE_H
